name: "Monorepo changelog with template"
description: "Generate changelog for multi-scope projects (monorepos) lerna supported"
author: "arpitBhalla"
branding:
  icon: "file-text"
  color: "blue"
inputs:
  GITHUB_AUTH:
    description: "Personal Access Token with read permission"
    required: true
    default: ""
  from:
    description: "The current version of the project (SHA or Tag)"
    required: false
    default: ""
  to:
    description: "The next version of the project (SHA or Tag)"
    required: false
    default: ""
  template:
    description: "Handlebar template for Changelog"
    required: false
    default: "DefaultTemplate"
  version_name:
    description: " Title for unreleased commits (e.g. Unreleased)"
    required: false
    default: "Unreleased"
  repo:
    description: "Your `org/repo` on GitHub (automatically inferred from the package.json file)"
    required: false
    default: ""
  language:
    description: "Language of the changelog"
    required: false
    default: "Markdown"

outputs:
  changelog:
    description: "Generated changelog"
runs:
  using: "node16"
  main: "src/index.ts"
