name: "Changelog Action for monorepo"
description: "Lerna Monorepo Changelog Generator"
author: "arpitBhalla"
branding:
  icon: "file-text"
  color: "blue"
inputs:
  GITHUB_AUTH:
    description: "Personal Access Token with read permission"
    required: true
    default: ""
  from:
    description: "The current version of the project.(SHA or Tag)"
    required: false
    default: ""
  to:
    description: "The next version of the project.(SHA or Tag)"
    required: false
    default: ""
  template:
    description: "Handlebar template for Changelog"
    required: false
    default: "DefaultTemplate"
  version_name:
    description: "Version Name for current release"
    required: false
    default: "Unreleased"
  repo:
    description: "Url of repo"
    required: false
    default: ""
  language:
    description: "Language of the changelog"
    required: false
    default: "Markdown"

outputs:
  changelog:
    description: "Generated changelog"
runs:
  using: "node16"
  main: "src/index.ts"