name: "Changelog Action for monorepo"
description: "Lerna Monorepo Changelog Generator"
author: "arpitBhalla"
branding:
  icon: "file-text"
  color: "blue"
inputs:
  from:
    description: "A commit SHA or tag"
    required: false
  to:
    description: "A commit SHA or tag"
    required: false
    default: HEAD
  template:
    description: "Handlebar template for changelog"
    required: false
  nextVersion:
    description: "Version name for next release"
    required: false
    default: "Unreleased"
  # groupBy:
  #   description: "label | scope"
  #   required: false
  #   default: "scopes"
  language:
    description: "Language of changelog"
    required: false
    default: "Markdown"
  repo:
    description: ""
    required: false
outputs:
  changelog:
    description: "Generated changelog"
runs:
  using: "node16"
  main: "src/index.ts"
